// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: Chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_Chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_Chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_Chat_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_Chat_proto protoreflect.FileDescriptor

const file_Chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"Chat.proto\x12\x04chat\"\x1d\n" +
	"\aMessage\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body2\xde\x01\n" +
	"\vChatService\x12,\n" +
	"\fMessageUnary\x12\r.chat.Message\x1a\r.chat.Message\x124\n" +
	"\x12MessageServertream\x12\r.chat.Message\x1a\r.chat.Message0\x01\x125\n" +
	"\x13MessageClientStream\x12\r.chat.Message\x1a\r.chat.Message(\x01\x124\n" +
	"\x10MessageBiStreams\x12\r.chat.Message\x1a\r.chat.Message(\x010\x01B&Z$github.com/hryt430/gRPC-catchup/chatb\x06proto3"

var (
	file_Chat_proto_rawDescOnce sync.Once
	file_Chat_proto_rawDescData []byte
)

func file_Chat_proto_rawDescGZIP() []byte {
	file_Chat_proto_rawDescOnce.Do(func() {
		file_Chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Chat_proto_rawDesc), len(file_Chat_proto_rawDesc)))
	})
	return file_Chat_proto_rawDescData
}

var file_Chat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Chat_proto_goTypes = []any{
	(*Message)(nil), // 0: chat.Message
}
var file_Chat_proto_depIdxs = []int32{
	0, // 0: chat.ChatService.MessageUnary:input_type -> chat.Message
	0, // 1: chat.ChatService.MessageServertream:input_type -> chat.Message
	0, // 2: chat.ChatService.MessageClientStream:input_type -> chat.Message
	0, // 3: chat.ChatService.MessageBiStreams:input_type -> chat.Message
	0, // 4: chat.ChatService.MessageUnary:output_type -> chat.Message
	0, // 5: chat.ChatService.MessageServertream:output_type -> chat.Message
	0, // 6: chat.ChatService.MessageClientStream:output_type -> chat.Message
	0, // 7: chat.ChatService.MessageBiStreams:output_type -> chat.Message
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Chat_proto_init() }
func file_Chat_proto_init() {
	if File_Chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Chat_proto_rawDesc), len(file_Chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Chat_proto_goTypes,
		DependencyIndexes: file_Chat_proto_depIdxs,
		MessageInfos:      file_Chat_proto_msgTypes,
	}.Build()
	File_Chat_proto = out.File
	file_Chat_proto_goTypes = nil
	file_Chat_proto_depIdxs = nil
}
